CREATE TABLE `landQuality`(
                              `id` INT AUTO_INCREMENT COMMENT '序号' ,
                              `name` VARCHAR(255) DEFAULT NULL COMMENT '基地名称' ,
                              `area` VARCHAR(255) DEFAULT NULL COMMENT '划分区域' ,
                              `result` VARCHAR(255) DEFAULT NULL COMMENT '评定结果' ,
                              `rate_time` DATETIME DEFAULT NULL COMMENT '评定时间' ,
                              `rate_unit` VARCHAR(255) DEFAULT NULL COMMENT '评定单位' ,
                              `operator` VARCHAR(255) DEFAULT NULL COMMENT '操作人' ,
                              `operating_time` DATETIME DEFAULT NULL COMMENT '操作时间' ,
                              `land_position` VARCHAR(255) DEFAULT NULL COMMENT '地形部位' ,
                              `soil_thickness` DECIMAL(10,2) DEFAULT NULL COMMENT '有效土层厚度' ,
                              `texture` VARCHAR(255) DEFAULT NULL COMMENT '耕层质地' ,
                              `soil_weight` VARCHAR(255) DEFAULT NULL COMMENT '土壤容重' ,
                              `soil_structure` VARCHAR(255) DEFAULT NULL COMMENT '质地构型' ,
                              `nutrient_status` VARCHAR(255) DEFAULT NULL COMMENT '土壤养分状况' ,
                              `biodiversity` VARCHAR(255) DEFAULT NULL COMMENT '生物多样性' ,
                              `cleanliness` VARCHAR(255) DEFAULT NULL COMMENT '清洁程度' ,
                              `hinder` VARCHAR(255) DEFAULT NULL COMMENT '阻碍因素' ,
                              `irrigation` VARCHAR(255) DEFAULT NULL COMMENT '灌溉能力' ,
                              `drain_water` VARCHAR(255) DEFAULT NULL COMMENT '排水能力' ,
                              `forest_network` VARCHAR(255) DEFAULT NULL COMMENT '农田林网化程度' ,
                              `pH` DECIMAL(10,2) DEFAULT NULL COMMENT '酸碱度' ,
                              `surface_thickness` DECIMAL(10,2) DEFAULT NULL COMMENT '耕层厚度' ,
                              `salinization` VARCHAR(255) DEFAULT NULL COMMENT '盐渍化程度' ,
                              `groundwater_depth` DECIMAL(10,2) DEFAULT NULL COMMENT '地下水埋深' ,
                              `slope` VARCHAR(255) DEFAULT NULL COMMENT '田面坡度' ,
                              `height` DECIMAL(10,2) DEFAULT NULL COMMENT '海拔高度' ,
                              PRIMARY KEY (id)
) COMMENT = '耕地质量';
